///////////////////////////////////////
//ACTION MODULE
///////////////////////////////////////
import { ODId, ODManager, ODValidId, ODSystemError, ODManagerData, ODNoGeneric } from "./base"
import { ODWorkerManager, ODWorkerCallback, ODWorker } from "./worker"
import { ODDebugger } from "./console"

/**## ODActionImplementation `class`
 * This is an Open Discord action implementation.
 * 
 * It is a basic implementation of the `ODWorkerManager` used by all `ODAction` classes.
 * 
 * This class can't be used stand-alone & needs to be extended from!
 */
export class ODActionImplementation<Source extends string,Params extends object,Result extends object,WorkerIds extends string = string> extends ODManagerData {
    /**The manager that has all workers of this implementation */
    workers: ODWorkerManager<object,Source,Params,WorkerIds>

    constructor(id:ODValidId, callback?:ODWorkerCallback<object,Source,Params>, priority?:number, callbackId?:ODValidId){
        super(id)
        this.workers = new ODWorkerManager("descending")
        if (callback) this.workers.add(new ODWorker(callbackId ? callbackId : id,priority ?? 0,callback))
    }
    /**Execute all workers & return the result. */
    async run(source:Source, params:Params): Promise<Partial<Result>> {
        throw new ODSystemError("Tried to build an unimplemented ODResponderImplementation")
    }
}

/**## ODActionManagerIdConstraint `type`
 * The constraint/layout for id mappings/interfaces of the `ODActionManager` class.
 */
export type ODActionManagerIdConstraint = Record<string,{source:string,params:object,result:object,workers:string}>

/**## ODActionManager `class`
 * This is an Open Discord action manager.
 * 
 * It contains all Open Discord actions. You can compare actions with some sort of "procedure".
 * It's a complicated task that is divided into multiple functions.
 * 
 * Some examples are `ticket-creation`, `ticket-closing`, `ticket-claiming`, ...
 * 
 * It's recommended to use this system in combination with Open Discord responders!
 */
export class ODActionManager<IdList extends ODActionManagerIdConstraint = ODActionManagerIdConstraint> extends ODManager<ODAction<string,{},{},string>> {
    constructor(debug:ODDebugger){
        super(debug,"action")
    }

    get<ActionId extends keyof ODNoGeneric<IdList>>(id:ActionId): ODAction<IdList[ActionId]["source"],IdList[ActionId]["params"],IdList[ActionId]["result"],IdList[ActionId]["workers"]>
    get(id:ODValidId): ODAction<string,{},{},string>|null
    
    get(id:ODValidId): ODAction<string,{},{},string>|null {
        return super.get(id)
    }

    remove<ActionId extends keyof ODNoGeneric<IdList>>(id:ActionId): ODAction<IdList[ActionId]["source"],IdList[ActionId]["params"],IdList[ActionId]["result"],IdList[ActionId]["workers"]>
    remove(id:ODValidId): ODAction<string,{},{},string>|null
    
    remove(id:ODValidId): ODAction<string,{},{},string>|null {
        return super.remove(id)
    }

    exists(id:keyof ODNoGeneric<IdList>): boolean
    exists(id:ODValidId): boolean
    
    exists(id:ODValidId): boolean {
        return super.exists(id)
    }
}

/**## ODAction `class`
 * This is an Open Discord action.
 * 
 * It is a collection of functions/workers to execute a complex workflow (e.g. creating a ticket, banning a user, ...).
 * 
 * Can be used standalone.
 */
export class ODAction<Source extends string,Params extends object,Result extends object,WorkerIds extends string = string> extends ODActionImplementation<Source,Params,Result,WorkerIds> {
    /**Run this action */
    async run(source:Source, params:Params): Promise<Partial<Result>> {
        //create instance
        const instance = {}
        
        //wait for workers to finish
        await this.workers.executeWorkers(instance,source,params)

        //return data generated by workers
        return instance
    }
}